version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: security_api_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:13
    container_name: security_api_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: security_api_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge
